import { Schedule } from "./classes/schedule"
import { AcademicYearConfig, SemesterConfig } from "./config/config"


let schedule = new Schedule("Model Schedule", AcademicYearConfig["AY2021-2022"])
console.log('INITIALISED')
schedule.initialiseSemesters(2)
// console.log(schedule)
console.log('HAS SEM', schedule.hasSemester(2, 2))
console.log('NO SEM', schedule.hasSemester(5, 1))
console.log('ADD EXISTING SEM', schedule.addSemester(4, 2))
console.log('ADD NEW SEM', schedule.addSemester(5, 1))
console.log('CHECK NEW SEM', schedule.hasSemester(5, 1))
console.log('REMOVE NON SEM', schedule.removeSemester(6, 1))
console.log('REMOVE SEM', schedule.removeSemester(5, 1))
console.log('CHECK SEM REMOVED', schedule.hasSemester(5, 1))
console.log(schedule)
console.log('\n\nMODULES')
console.log('add mod', schedule.addModule('PC2130', 2, 2))
console.log('add existing mod', schedule.addModule('PC2130', 2, 2))
console.log('add new mod', schedule.addModule('ESP2107', 2, 2))
console.log('add new mod', schedule.addModule('ESP2111', 1, 2))
console.log('add new mod', schedule.addModule('ESP2106', 2, 2))
console.log('check mod', schedule.hasModule('PC2130'))
console.log(schedule)
console.log('remove non mod', schedule.removeModule('PC2130', 1, 1))
console.log('remove non mod', schedule.removeModule('PC2133', 2, 2))
console.log('remove mod', schedule.removeModule('PC2130', 2, 2))
console.log('check mod', schedule.hasModule('PC2130'))
console.log(schedule)
console.log(schedule.flatten())